<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",872,907);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1238,1443);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",1631,1660);
$z[4][4]['name']="position";
$z[5]=Array("field","",1744,1763);
$z[5][4]['name']="title";
$z[6]=Array("field","",1807,1827);
$z[6][4]['name']="source";
$z[7]=Array("field","",1845,1863);
$z[7][4]['name']="body";
$z[8]=Array("include","",2714,2751);
$z[8][4]['filename']="footer.htm";

?>