<?php
$z[0]=Array("channelartlist","\r\n	  <ul>\r\n		{dede:channelartlist typeid='top' row='8'}\r\n		<li class='strong'><a href='{dede:field name='typeurl'/}'>{dede:field name='typename' /}</a></li>\r\n        {dede:channel type='son' noself='yes'}\r\n		<li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n		{/dede:channel}\r\n      </ul>\r\n	  ",91,458);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",549,572);
$z[1][4]['name']="cfg_zxdh";
$z[2]=Array("global","",1042,1068);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",1082,1106);
$z[3][4]['name']="cfg_beian";

?>