<?php
$z[0]=Array("channelartlist","\r\n		<li><a class='a' href='{dede:field name='typeurl'/}'>{dede:field name='typename' /}</a>\r\n          <div class='erji'>\r\n		    {dede:channel type='son' noself='yes'}\r\n            <p><a href='[field:typelink/]'>[field:typename/]</a></p>\r\n			{/dede:channel}\r\n          </div>\r\n        </li>\r\n		",230,588);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";

?>