<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1040,1075);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\r\n	    <li><a href=\"[field:arcurl/]\">\r\n        <dl>\r\n          <dt><img src=\"[field:picname/]\" width=\"124\" height=\"121\" /><span>产品</span></dt>\r\n          <dd>[field:title/]</dd>\r\n        </dl>\r\n        </a> \r\n		</li>\r\n		",2415,2718);
$z[2][4]['typeid']="10";
$z[2][4]['row']="4";
$z[2][4]['titlelen']="20";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n		",2912,3113);
$z[3][4]['typeid']="10";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="30";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("include","",3158,3195);
$z[4][4]['filename']="footer.htm";

?>