<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1402,1437);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1769,1974);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",2163,2192);
$z[4][4]['name']="position";
$z[5]=Array("field","",2384,2405);
$z[5][4]['name']="content";
$z[6]=Array("include","",2467,2504);
$z[6][4]['filename']="footer.htm";

?>