<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",871,906);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1235,1440);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",1630,1659);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n		  <li><A href=\"\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\" width=\"171\" height=\"91\" /></A></li>\r\n		  ",1723,1889);
$z[5][4]['pagesize']="12";
$z[6]=Array("pagelist","",1932,1988);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2040,2077);
$z[7][4]['filename']="footer.htm";

?>