<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",872,907);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1231,1436);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",1626,1655);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n		 <dl>\r\n          <dt><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"175\" height=\"129\" /></a></dt>\r\n          <dd>\r\n            <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n            <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n            <p>[field:infos/]...</p>\r\n            <a href=\"[field:arcurl/]\" class=\"more\">更多</a> </dd>\r\n        </dl>\r\n		",1703,2151);
$z[5][4]['pagesize']="4";
$z[5][4]['infolen']="300";
$z[6]=Array("pagelist","",2179,2235);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2287,2324);
$z[7][4]['filename']="footer.htm";

?>