<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",872,907);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1236,1441);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",1631,1660);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n		  <li><A href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"219\" height=\"162\" /></A><span>[field:title/]</span></li>\r\n		  ",1725,1894);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",1937,1993);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2045,2082);
$z[7][4]['filename']="footer.htm";

?>