<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1619,1654);
$z[1][4]['filename']="head.htm";
$z[2]=Array("channelartlist","\r\n		    <li>\r\n            <h2><a href='{dede:field name='typeurl'/}'>{dede:field name='typename' /}</a></h2>\r\n            {dede:channel type='son'  noself='yes'}\r\n			<a href='[field:typelink/]'>[field:typename/]</a><span>|</span>\r\n			{/dede:channel}\r\n			</li> \r\n			",2360,2679);
$z[2][4]['type']="top";
$z[3]=Array("include","",2743,2780);
$z[3][4]['filename']="footer.htm";

?>