<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",872,907);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1242,1447);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("field","",1636,1665);
$z[4][4]['name']="position";
$z[5]=Array("include","",6544,6581);
$z[5][4]['filename']="footer.htm";

?>